export default {
  swedish: {
    argentina: 'argentina',
    australia: 'australien',
    brazil: 'brasilien',
    cuba: 'kuba',
    france: 'frankrike',
    germany: 'tyskland',
    italy: 'italien',
    japan: 'japan',
    korea: 'korea',
    mexico: 'mexiko',
    netherlands: 'nederländerna',
    romania: 'rumäninen',
    russia: 'ryssland',
    spain: 'spanien',
    sweden: 'sverige',
    thailand: 'thailand',
    ukraine: 'ukraina',
    usa: 'usa',
  },
  korean: {
    argentina: '아르헨티나',
    australia: '호주',
    brazil: '브라질',
    cuba: '쿠바',
    france: '프랑스',
    germany: '독일',
    italy: '이탈리아',
    japan: '일본',
    korea: '한국',
    mexico: '멕시코',
    netherlands: '네덜란드',
    romania: '루마니아',
    russia: '러시아',
    spain: '스페인',
    sweden: '스웨덴',
    thailand: '태국',
    ukraine: '우크라이나',
    usa: '미국',
  },
};
